### ISSUE TITLE
[epic-Incident Management]

### ISSUE THREAD

**Issue by lioramilbaum** [devopsloft/dpline#1]
Delivery Pipeline is a multi sub-services service. Each sub-service may through alerts when hitting a failure or close to hitting one.

The alerts should be pushed to a one and only one queue. This is the first sub-service.

The queue should be able to:

- Consume the alerts and transform them to incidents

- Analyze the alerts - removing false/positives and aggregation of similar alerts

- Tracking incidents are resolved according to SLA

- Remediation by automation

**Comment by lioramilbaum** [comment]
Are we taking care of spawning the environment or starting from an existing environment?

**Comment by bregman-arie** [comment]
I would vote for taking care of the spawning as it makes it easier to test the project in the future + best customer experience :D

**Comment by lioramilbaum** [comment]
+1
